apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mukasa/ms-ticket-auth
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          env:
            - name: MONGO_SERVER
              vaue: auth-mongo-srv
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: jwtkey
                  name: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: auth
