apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: mukasa/ms-tickets-tickets
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          env:
            - name: MONGO_SERVER
              value: tickets-mongo-srv
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwtkey
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: tickets
